### ISSUE TITLE
Cannot find type definition file for 'jasmine'

### ISSUE THREAD

**Issue by city41** [jjherscheid/ts-mocks#10]
Thanks for this library, it's super useful.

I am using it with jest, and I am getting `Cannot find type definition file for 'jasmine'`. But if I install `@types/jasmine`, they conflict with `@types/jest` as they both declare global `describe`, `it`, etc.

Has anyone else hit this? I'm trying to find a solution and no luck so far.

**Comment by city41** [comment]
This seems to be a common problem with TypeScript and globals. TS 2.0+ allows definition files to redeclare globals, but they must exactly match, type-wise. Jest and Jasmine have a lot of the same global names, but with different types.  
  
I was able to work around the problem by adding `skipLibCheck: true` to compilerOptions in my tsconfig.  
  
@jjherscheid what do you think of switching in Sinon for Jasmine? Sinon doesn't introduce any globals and would then allow ts-mocks to be more compatible with other testing frameworks. I could probably create a PR for that.

**Comment by jjherscheid** [comment]
Hi @city41, Sorry I was not able to reply during the weekend! Great to hear that you like the package. And great that you have found a solution for now. I work a lot with Jasmine and do not really know Sinon. And I also know that a lot of users do use Jasmine and I don't want to put them al on sinon. 
But what you could do also is just fork this repo en create for-example a ts-mocks-sinon package yourself. And I could even mention that in the readme. What do you think? I know there is also a ts-mocks-wallaby package.

**Comment by ike18t** [comment]
You could create spy adapters (with Jasmine being the default) and have a
static configuration method for allowing overrides. You'll just have to
provide an interface for the adapters to implement as well as write an
implementation for Jasmine spies using said interface.

**Comment by Shane-E** [comment]
I also ran into this recently, @city41 workaround seems to be fine for now, maybe this incompatibility should be noted on the readme so that others considering ts-mocks know that it requires additional work to be used with jest.

**Comment by jjherscheid** [comment]
@Shane-E , @ike18t created another mocking framework 'ts-mockery' (https://github.com/ike18t/ts-mockery) which is compatible with jest. Good point for mention this in the readme. I will do that.

**Comment by ike18t** [comment]
Hoping to have time to work on the ts-mockery README this weekend.  🤞🏻

**Comment by ike18t** [comment]
☝️Done.
