### ISSUE TITLE
.extend does not work

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [jjherscheid/ts-mocks#18]
I have the following setup:

` let mockedHttpClient: Mock<HttpClient>;
  beforeEach(() => {
    mockedHttpClient = new Mock<HttpClient>({ get: () => of(new Array<Stuff>()) });
  });`

 `beforeEach(async(() => {
    TestBed.configureTestingModule({
      providers: [ApiService, { provide: HttpClient, useValue: mockedHttpClient.Object }]
    });
  }));`

When I want to use extend in a test method like this:

`it('should return one stuff', () => {
    let stuffs = new Array<Stuff>();
    stuffs.push(new Stuff("a")); 
    mockedHttpClient.extend(({ get: () => of(stuffs) });
    apiService.getStuff().subscribe((data: Array<Stuff>) => {
      expect(data.length).toBe(0);
    });
  });`

The extend does not work. So it returns the inital value assigend in the beforeEach.

**Comment by ike18t** [comment]
Extend totally works.  What you are missing here is that when you setup the TestBed it actually makes a clone of your object which means that you are mutating the wrong object.  You need to pull the object out of TestBed via TestBed#get and extend it.

Also I noticed you are mocking HttpClient, Angular supplies a testing module for that situation:
https://angular.io/api/common/http/testing/HttpTestingController
https://medium.com/netscape/testing-with-the-angular-httpclient-api-648203820712

**Comment by jjherscheid** [comment]
I agree with @ike18t, so I will close the issue.

**Comment by mariomurrent-softwaresolutions** [comment]
Awesome thanks 👍 

Well the HttpClient was just an example, Don't want to paste production code in here

**Comment by mariomurrent-softwaresolutions** [comment]
Awesome thx.

The HttpClient was just an example as I don't want to post production code in here :)

**Comment by sgwatgit** [comment]
I can't find any examples of how you would pull the original Mock about of the `TestBed`. The `TestBed` only has the `mock.Object`, not the original mock. There is no `.extend()` on the object pulled out of `TestBed`.

It doesn't look like the unit tests provide any examples of using `TestBed`.

Is there something I'm missing here?

**Comment by mariomurrent-softwaresolutions** [comment]
That's true. I haven't figured out yet how to pull the mock out ...

**Comment by jjherscheid** [comment]
Hi guys, it should be working, I will try to creatie an example for you today!

**Comment by jjherscheid** [comment]
Hi guys, it should be working, I will try to creatie an example for you today!

**Comment by mariomurrent-softwaresolutions** [comment]
> Hi guys, it should be working, I will try to creatie an example for you today!

Thank you very much

**Comment by jjherscheid** [comment]
Here is a Gist file with my sample code: https://gist.github.com/jjherscheid/52ec2c5cc4cfe242dc8b0fe02db2eea4

**Comment by jjherscheid** [comment]
readme.md updated ;-)

**Comment by mariomurrent-softwaresolutions** [comment]
I just created a new test, like yours in the gist file and it works. Maybe its a typescript issue on my side.

**Comment by jjherscheid** [comment]
> I just created a new test, like yours in the gist file and it works. Maybe its a typescript issue on my side.

Great! If there is something I can help with please let me know ;)
