### ISSUE TITLE
'lib' folder is missing in version 2.3.1

### ISSUE THREAD

**Issue by HolgerPersch** [jjherscheid/ts-mocks#19]
After installing version "2.3.1" all "ts-mocks" imports are broken because the "lib" folder is missing in "node_modules".

![image](https://user-images.githubusercontent.com/5908383/46654415-152d4500-cba9-11e8-9662-ba770c8fc534.png)

**Comment by jjherscheid** [comment]
Oh... my bad.. I am going to fix this directly

**Comment by jjherscheid** [comment]
Sorry for this. :(. I updated to 2.3.2 with lib folder.
