### ISSUE TITLE
ReferenceError: spyOn is not defined

### ISSUE THREAD

**Issue by Ahmds3ed** [jjherscheid/ts-mocks#2]
ReferenceError: spyOn is not defined using ts-mocks when trying to setup method 

here is code :
var authService = new Mock<AuthService>();
    authService.setup(au => au.parseToken).returns(() => { return {iss: ''}});

error : 
PS C:\Users\saiedali\Documents\frontend> npm test

> DC_ServiceSd@ test C:\Users\saiedali\Documents\frontend
> mocha -r ts-node/register test/unit/ts/services/settings-srv-tst.ts

C:\Users\saiedali\Documents\frontend\node_modules\ts-mocks\lib\mocks\setup.js:9
        this.spy = spyOn(this.object, key);
                   ^
ReferenceError: spyOn is not defined

**Comment by jjherscheid** [comment]
Strange! Do you call the setup inside a Jasmine method? Like the 'beforeEach' or the 'it' ?
