### ISSUE TITLE
Cannot import ts-mocks correctly with Rollup

### ISSUE THREAD

**Issue by martindzejky** [jjherscheid/ts-mocks#20]
`Error: 'Mock' is not exported by node_modules/ts-mocks/lib/index.js`

This error happens in my project. It is using Karma, Rollup, and Typescript. Here's my `tsconfig.json` file:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "ES2015",
        "sourceMap": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "inlineSourceMap": true,
        "lib": ["es2015", "dom"],
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,
        "strictNullChecks": true
    }
}
```

Let me know if you need any further information.

**Comment by jjherscheid** [comment]
Hi @martindzejky , I am new to Rollup, so I have to look into the problem. So I will try to see if I have the same problems. Do you have it on one of your repositories (so I can fork it?). Otherwise I will try to create a project myself.

**Comment by martindzejky** [comment]
Hey @jjherscheid, this is a private project so I cannot provide you with any code. However, I suspect that the problem might be that you use `module: commonjs` in your `tsconfig` while I use `module: es2015`. 🤔

**Comment by jjherscheid** [comment]
That could be indeed be a problem. Maybe something like https://github.com/rollup/rollup-plugin-commonjs will fix your problem. However I would still like to look into the problem ;-)

**Comment by martindzejky** [comment]
I am already using that plugin. I'll try to make a small repo which reproduces the issue.

**Comment by jjherscheid** [comment]
Hi, did you have time to create a small repo with the issue?
