### ISSUE TITLE
getPropertyName does not support ES2015

### ISSUE THREAD

**Issue by escorter** [jjherscheid/ts-mocks#21]
The function `getPropertyName` does not support ES2015 arrow functions when there is no return statement. This does affect the `setup` and `spyOf` method.

Working:
`const spy = myMock.spyOf(x => {
  return x.myFunction;
});`

Not working:
`const spy = myMock.spyOf(x => x.myFunction);`

**Comment by jjherscheid** [comment]
Do you mean that de usage should be described in the readme? Of should I change something in the library?

**Comment by escorter** [comment]
I think as a quick-fix one you might mention it in the readme as it clashes with the angular8 standard package setting so there might be more people stumbling over it.
As long-term solution you might change the regular expression to handle also arrow functions or switch to the approach jasmine uses by handing in a string.

**Comment by jjherscheid** [comment]
Ah.. Thanks for the info. I will look into this. If you have a solution ready feel free to create PR 😉

**Comment by escorter** [comment]
I have created https://github.com/jjherscheid/ts-mocks/pull/22 
It works with ES5 and ES2015 compiler target, you can toggle it in the tests but only one target at a time can be used

**Comment by jjherscheid** [comment]
Wow.. that was fast. But the target does not affect the regular expression wright? So the regular expresion can alway be use like how you specified.

**Comment by escorter** [comment]
Yes, it detects either the return keyword as it was or the => function.
The problem was that with the ES5 target the arrow functions in the javascript code got transpiled into the old return ... style so it was working, but when using ES2015 the arrow functions stays as-is and the regex with just the return statement do not find them

**Comment by jjherscheid** [comment]
I am currently adding it to the master and testing is. (version update etc..) so I will push soon the new npm version ;-)

**Comment by escorter** [comment]
One more remark on that. I saw that this also affects the .setup method, it stops working with ES2015. Maybe you want also to test that but as far as I have seen it is all covered by unit tests

**Comment by jjherscheid** [comment]
Yes. the unit test should cover all scenario's. What I have done now it added an extra karma conf and test both es2015 and es.

**Comment by jjherscheid** [comment]
I've update the code including double tests, merged de PR #22 and published to NPM ;-).
Tanx for the support!

**Comment by jjherscheid** [comment]
Somehow the wrong version of the output files was added to npm. I have fixed is with version 2,4,0
