### ISSUE TITLE
Spelling in readme file

### ISSUE THREAD

**Issue by sverkunov** [jjherscheid/ts-mocks#25]
There are some spelling errors in the readme file. 
I've created a pull request for it.

**Comment by jjherscheid** [comment]
> There are some spelling errors in the readme file.
> I've created a pull request for it.

I don't see the pull request. Are you sure you created it?

**Comment by jjherscheid** [comment]
Update the library today and fixed the typos (hopefully ;-))

**Comment by sverkunov** [comment]
Didn't push yesterday since don't have a permission

**Comment by jjherscheid** [comment]
No problem.. it triggers me to check for the typos ;-)
