### ISSUE TITLE
Unexpected error when running tests

### ISSUE THREAD

**Issue by kevkcc** [jjherscheid/ts-mocks#29]
Environment: Angular 9, typescript 3.7.5

ERROR in node_modules/ts-mocks/lib/mocks/mock.d.ts:44:70 - error TS2314: Generic type 'Calls<Fn>' requires 1 type argument(s).

44     callsOf<TProp>(value: (obj: T) => TProp, propertyName?: string): jasmine.Calls;

Works if you add a type to the generic type for jasmine.Calls

**Comment by jjherscheid** [comment]
I am looking into the issue. Seems like this is because of some changes in jasmine. 
You can use version 2.6.1 for now. (only the methods callsOf and resetCalls are not available then.

**Comment by jjherscheid** [comment]
Due to the newest @types/jasmine 3.5.9 the Jasmine.Calls must have a generic argument.
It is also possible to set the @types/jasmine back to the version before which is 2.5.41. Then it also works.
I am still trying to figure out if there's a alternative solution....

**Comment by jjherscheid** [comment]
Updated code to 3.0.1. The callsOf method no returns a 'any' instead of jasmine.Calls.
I don't like the any, but cannot think of a better solution right now to be compatible with the old and new @types/jasmine declarations.

**Comment by jjherscheid** [comment]
@kevkcc did this work for you?

**Comment by kevkcc** [comment]
@jjherscheid Yes it did, appreciate the help
