### ISSUE TITLE
different Mock setup in each test

### ISSUE THREAD

**Issue by rmeshksar** [jjherscheid/ts-mocks#3]
Hi,
the following is the beforeEach method of my unit test:

```javasvript

  let mockService1: Mock<Service1>;
  let service: ServiceUnderTest;


  beforeEach(() => {
    mockService1= new Mock<Service1>();
    mockService1.setup(x => x.myObject)
      .is({
        a: {
          b: '',
          c: ''
        }
      });

    TestBed.configureTestingModule({
      providers: [
        ServiceUnderTest,
        { provide: Service1, useValue: mockService1.Object }
      ]
    });

    service = TestBed.get(ServiceUnderTest);
  });
```

The question how I can have different setup for mockService1 in each test.

Thanks.

**Comment by jjherscheid** [comment]
Hi,
You can call mockService1.setup() multiple times.. The last will win. So what I do is setup the default behavior for most tests in the beforeEach().. And every time I want to change the behavior inside a it() you can just changed it inside the test with a new .setup().

Good luck

**Comment by rmeshksar** [comment]
Thanks for the reply.
I was doing the same thing but it was not working, meaning the value of the myObject of Service1 was undefined.

Since it is the test of a service, in beforeEach, instead of using TestBed, I used:

service = new ServiceUnderTest(mockService1.Object) and now it works.

**Comment by jjherscheid** [comment]
Hi,
Most of the time I don't use Testbed if it is not needed :-).. 
But I think this behavior is due to the 'useValue' in the providers. Maybe it will work if you use 'useFactory' because I think that useValue evaluates one time.

**Comment by ike18t** [comment]
Angular DI will make a copy of the object you are providing via DI.  You will need to TestBed.get your mocked service out so you can construct a new Mock with it for extension.  Doing this will mutate the reference that is in TestBed.
