### ISSUE TITLE
Generic methods cannot be mocked easily

### ISSUE THREAD

**Issue by jjherscheid** [jjherscheid/ts-mocks#9]
When objects have generic methods it is not easy to mock.
For now you must use the following syntax:

mf.setup(f => f.fightersGeneric).Spy.and.returnValue('tada');

or use the spyOf method to use a spy.

But still looking for other solution to be typesafe....

**Comment by ike18t** [comment]
Aww man... you lose type safety.  I'd rather:
const mock = new Mock<Foo>({fightersGeneric: function<T>(arg: T) { return {} as T} });

**Comment by jjherscheid** [comment]
I was just looking for a solution... I could not found anything working... 
Will your solution work?

**Comment by jjherscheid** [comment]
This will also work.. Is the same as @ike18t but with arrow function:
const mock = new Mock<Foo>({ fightersGeneric: <T>(arg: T) => ({} as Mock<T>) })

**Comment by jjherscheid** [comment]
Problem is with both solutions is that when you fill in the {} with params... Like:

![image](https://user-images.githubusercontent.com/17475138/37970335-7c0d29e0-31d3-11e8-9744-9e544dbdd2d7.png)

**Comment by ike18t** [comment]
I can't see the rest of the code.  That definitely would cause an error though being that T is not defined to extend anything and you are casting an object with properties declared.

**Comment by jjherscheid** [comment]
Basically someone in trying to mock the new HttpClient from Angular 4+ this has a method get<T> which returns Observable<HttpEvent<T>>.

get<T>(url: string, options: {
    headers?: HttpHeaders | {[header: string]: string | string[]},
    observe: 'events',
    params?: HttpParams|{[param: string]: string | string[]},
    reportProgress?: boolean,
    responseType?: 'json',
    withCredentials?: boolean,
  }): Observable<HttpEvent<T>>;

So T has no definition and can't be converted to anything.
Maybe I am missing something.. But I created this Issue to think about a (hopefully) typesafe solution to test methods like this ;-)...

It does not have to be fixed right away. :D

**Comment by ike18t** [comment]
Using ts-mocks seems like the wrong tool to use for that job.  Angular provides test helpers for mocking out http requests.
https://angular.io/api/http/testing/MockBackend

**Comment by jjherscheid** [comment]
Ha, yes I know.. I also told that ;-). But this triggered me to think about generic methods :D
